// The interviewer's voice, generated by a speech service so that every visitor hears the same
// natural voice with nothing to download. Optional: without a key the pages fall back to the
// browser's built-in voice.
//
//   VOICE_API_KEY   key for the speech service (turns this on)
//   VOICE_PROVIDER  "azure" (default) or "openai" (any service with OpenAI's /audio/speech API)
//   VOICE_REGION    Azure region, e.g. "centralindia" (azure only)
//   VOICE_NAME      which voice; defaults to a male conversational one
//   VOICE_MODEL     model id (openai-style only)
//   VOICE_BASE_URL  override the service address (openai-style services other than OpenAI)
//   VOICE_DAILY_CHARS  characters spoken per day across all users before falling back (default 15000,
//                      which keeps a month inside Azure's free allowance)

const { prisma } = require('./prismaClient');
const { AppError } = require('./appError');
const { stripControl } = require('./text');

const PROVIDER = (process.env.VOICE_PROVIDER || 'azure').toLowerCase();
const API_KEY = process.env.VOICE_API_KEY || '';
const REGION = process.env.VOICE_REGION || 'eastus';
const NAME = process.env.VOICE_NAME || (PROVIDER === 'azure' ? 'en-US-AndrewNeural' : 'onyx');
const MODEL = process.env.VOICE_MODEL || 'gpt-4o-mini-tts';
const BASE_URL = (process.env.VOICE_BASE_URL || '').replace(/\/+$/, '');
const DAILY_CHARS = Number(process.env.VOICE_DAILY_CHARS) > 0 ? Number(process.env.VOICE_DAILY_CHARS) : 15000;

const MAX_SENTENCE_CHARS = 600;       // one spoken sentence; the interviewer's are far shorter
const MAX_INTERVIEW_CHARS = 12000;    // several times what a full interview says
const TIMEOUT_MS = 10000;

const voiceEnabled = !!API_KEY && (PROVIDER === 'azure' || PROVIDER === 'openai');

// Characters spoken today, kept in memory and seeded from the database after a restart
let today = '';
let spokenToday = 0;

async function spokenSoFarToday() {
  const day = new Date().toISOString().slice(0, 10);
  if (day !== today) {
    const since = new Date(`${day}T00:00:00.000Z`);
    const sum = await prisma.interview.aggregate({ _sum: { voiceChars: true }, where: { updatedAt: { gte: since } } });
    today = day;
    spokenToday = sum._sum.voiceChars || 0;
  }
  return spokenToday;
}

const xml = (text) => text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');

async function fromAzure(text, signal) {
  const url = BASE_URL || `https://${REGION}.tts.speech.microsoft.com`;
  return fetch(`${url}/cognitiveservices/v1`, {
    method: 'POST',
    signal,
    headers: {
      'Ocp-Apim-Subscription-Key': API_KEY,
      'Content-Type': 'application/ssml+xml',
      'X-Microsoft-OutputFormat': 'audio-24khz-48kbitrate-mono-mp3',
      'User-Agent': 'AeroPrep'
    },
    body: `<speak version="1.0" xml:lang="${xml(NAME.slice(0, 5))}"><voice name="${xml(NAME)}">${xml(text)}</voice></speak>`
  });
}

async function fromOpenAIStyle(text, signal) {
  return fetch(`${BASE_URL || 'https://api.openai.com/v1'}/audio/speech`, {
    method: 'POST',
    signal,
    headers: { Authorization: `Bearer ${API_KEY}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ model: MODEL, voice: NAME, input: text, response_format: 'mp3' })
  });
}

/**
 * One sentence of the interviewer's speech as audio. Only for the caller's own interview, and
 * only within the caps, so this cannot be used as a free speech service.
 * @returns {Promise<{audio: Buffer, type: string}>}
 */
async function speak(interviewId, userId, rawText) {
  if (!voiceEnabled) throw new AppError(404, 'VOICE_OFF', 'The natural voice is not set up.');
  const text = stripControl(rawText).replace(/\s+/g, ' ').trim().slice(0, MAX_SENTENCE_CHARS);
  if (!text) throw new AppError(400, 'EMPTY_TEXT', 'Nothing to say.');

  const interview = await prisma.interview.findFirst({ where: { id: interviewId, userId }, select: { id: true, voiceChars: true } });
  if (!interview) throw new AppError(404, 'NOT_FOUND', 'Interview not found');
  if (interview.voiceChars + text.length > MAX_INTERVIEW_CHARS || (await spokenSoFarToday()) + text.length > DAILY_CHARS) {
    throw new AppError(429, 'VOICE_LIMIT', 'The natural voice has reached its limit for now.');
  }

  // Counted before the call: a request that fails half way may still have been charged
  spokenToday += text.length;
  await prisma.interview.update({ where: { id: interview.id }, data: { voiceChars: { increment: text.length } } });

  let response;
  try {
    const signal = AbortSignal.timeout(TIMEOUT_MS);
    response = await (PROVIDER === 'azure' ? fromAzure(text, signal) : fromOpenAIStyle(text, signal));
  } catch (error) {
    console.error(`[Voice] ${PROVIDER} could not be reached: ${error.message}`);
    throw new AppError(502, 'VOICE_UNAVAILABLE', 'The natural voice is not available right now.');
  }
  if (!response.ok) {
    console.error(`[Voice] ${PROVIDER} answered ${response.status}: ${(await response.text()).slice(0, 200)}`);
    throw new AppError(502, 'VOICE_UNAVAILABLE', 'The natural voice is not available right now.');
  }
  return { audio: Buffer.from(await response.arrayBuffer()), type: response.headers.get('content-type') || 'audio/mpeg' };
}

module.exports = { voiceEnabled, speak, describeVoice: () => (voiceEnabled ? `${PROVIDER}/${NAME}` : 'browser voice (set VOICE_API_KEY for a natural one)') };
